### ISSUE TITLE
Crash on start with exit code 0

### ISSUE THREAD

**Issue by Plasmeur** [WRLTech/Less-Tech-More-Dragon#4]
When i try to start the pack, it open FML loading window, and after loading some mods, just crash with exit code 0 into the launcher. I only get this log, the latest.log : https://gist.github.com/Plasmeur/29d0a97e005afedd7ab26f8902157027

**Comment by Rutes** [comment]
Hi there. Can you use https://gist.github.com/ instead of posting logs here?
Also, make sure to include your crash report, latest.log, and debug.log, as separate files in the gist

**Comment by Plasmeur** [comment]
done

**Comment by Plasmeur** [comment]
So have you any idea of how i can patch this or play with the pack ?

**Comment by Plasmeur** [comment]
ok so finally i found the source of the problem it was a known bug while installing minecraft and using forge modpack on curseforge. when this happens, you should delete the "Install" file and restart curseforge.
