### ISSUE TITLE
Crash after placing Ceramics pipe

### ISSUE THREAD

**Issue by Talonflamex** [WRLTech/Less-Tech-More-Dragon#5]
[crash-2021-02-01_12.20.55-client.txt](https://github.com/WRLTech/Less-Tech-More-Dragon/files/5906552/crash-2021-02-01_12.20.55-client.txt)

I was on the server and decided to try using pipes from the mod Ceramics to decorate, but after placing one the game crashed. Now I can't log into the server at all.

**Comment by Rutes** [comment]
will see if this is fixed with newer version
